/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class iniciarsesion extends javax.swing.JFrame {
    private Inicio splashframe;

    public  iniciarsesion(Inicio splashframe) {
       this.splashframe=splashframe;
       setProgress(0);
       initComponents();
       pass.setVisible(false);
       llamada.setVisible(false);
       setProgress(20);
        setProgress(30);
       setProgress(40); 
         setProgress(50);
       setProgress(60);
        setProgress(70);
       setProgress(80);
       setProgress(90);
       setProgress(100);
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(1600,800));
        //this.setExtendedState(iniciarsesion.MAXIMIZED_BOTH);
    }
    public iniciarsesion() {
        initComponents();
        pass.setVisible(false);
    }
    
    private void setProgress(int percent){
   
    splashframe.getJProgressBar().setValue(percent);
    try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paneladmin = new org.edisoncor.gui.panel.PanelRound();
        zzzzzzzz = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        llamada = new org.edisoncor.gui.panel.PanelLlamada();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logosesion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 270, 190));

        paneladmin.setColorPrimario(new java.awt.Color(0, 51, 51));
        paneladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneladminMouseClicked(evt);
            }
        });
        paneladmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zzzzzzzz.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        zzzzzzzz.setForeground(new java.awt.Color(255, 255, 255));
        zzzzzzzz.setText("Iniciar como");
        paneladmin.add(zzzzzzzz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 50));

        user.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        user.setText("Administrador");
        paneladmin.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 40));

        jPanel1.add(paneladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 230, 130));

        pass.setToolTipText("Ingrese la contraseña");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 210, 40));

        llamada.setColorPrimario(new java.awt.Color(0, 204, 255));
        llamada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desactive la Tecla Mayus");
        llamada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jPanel1.add(llamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 180, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 6, 1520, 772));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladminMouseClicked
        pass.setVisible(true);
    }//GEN-LAST:event_paneladminMouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        String usuario= user.getText().toString();
        String contra= pass.getText().toString();
    
    if(usuario.equals("Administrador")&& contra.equals("123")){
        
        Escritorio escri= new Escritorio();
        escri.setVisible(true);
        hide();
    }else{
        JOptionPane.showMessageDialog(null, "Contraseña Incorrecta","Error",JOptionPane.WARNING_MESSAGE);
       
    }
    }//GEN-LAST:event_passActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if(pass.getText().matches("[A-Z]*")){
            llamada.setVisible(true);
            
        }
         if(pass.getText().matches("[a-z]*")){
            llamada.setVisible(false);
            
        }
        
    }//GEN-LAST:event_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciarsesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelLlamada llamada;
    private org.edisoncor.gui.panel.PanelRound paneladmin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel user;
    private javax.swing.JLabel zzzzzzzz;
    // End of variables declaration//GEN-END:variables
}
