/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso;

import chrriis.common.UIUtils;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author Richard
 */
public class navegador extends javax.swing.JFrame {

    /**
     * Creates new form navegador
     */
    public navegador() {
        initComponents();
        this.setSize(new Dimension(1600,800));
        //this.setExtendedState(navegador.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(navegador.HIDE_ON_CLOSE);
        JPanel webBrowserPanel = new JPanel(new BorderLayout());
        final JWebBrowser navega= new JWebBrowser();
        navega.navigate("http://www.google.com.pe");
        webBrowserPanel.add(navega);
        add(webBrowserPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
       UIUtils.setPreferredLookAndFeel();
    NativeInterface.open();
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
      navegador p=new navegador();
      p.setVisible(true);
      p.setBounds(0,0,400,400);
      p.setDefaultCloseOperation(EXIT_ON_CLOSE);
      }
    });
    NativeInterface.runEventPump();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
